import {
  pgTable,
  text,
  integer,
  timestamp,
  jsonb,
  uuid,
  numeric,
} from "drizzle-orm/pg-core";
import { z } from "zod/v4";

export type CampaignPlatform = "google" | "instagram" | "facebook" | "tiktok";
export type CampaignStatus = "rascunho" | "ativa" | "pausada" | "encerrada";

/** Payment state of the campaign budget (paid in Kz by the owner). */
export type CampaignPaymentStatus = "nao_pago" | "pendente" | "pago" | "falhado";
/** State of the AI-generated ad creative. */
export type CampaignCreativeStatus = "nenhum" | "a_gerar" | "pronto" | "erro";
/** State of the real ad published through the ads gateway (Zernio). */
export type CampaignPublishStatus =
  | "nao_publicada"
  | "a_publicar"
  | "em_revisao"
  | "ativa"
  | "pausada"
  | "encerrada"
  | "rejeitada"
  | "erro";

/** AI-generated ad creative (copy + media) ready for publication. */
export interface AdCreative {
  /** Products from the catalog the creative is built around. */
  productNames: string[];
  headline: string;
  body: string;
  /** Gateway CTA enum, e.g. SHOP_NOW, LEARN_MORE. */
  callToAction: string;
  /** "image" (Meta) or "video" (TikTok). */
  mediaType: "image" | "video";
  /** Served via /api/storage/objects/... */
  mediaUrl: string;
  /** Prompt/concept used, for regeneration transparency. */
  concept: string;
  generatedAt: string;
}

/** Copy variant generated by the AI. */
export interface CampaignCopy {
  headline: string;
  body: string;
  cta: string;
}

/** Full strategy kit per platform. */
export interface CampaignKit {
  audience: {
    demographics: string;
    interests: string;
    behaviours: string;
    excludedAudiences: string;
  };
  budgetAllocation: {
    suggestion: string;
    dailyBudget: string;
    bidStrategy: string;
  };
  copies: CampaignCopy[];
  creativeBrief: {
    format: string;
    visualConcept: string;
    doList: string[];
    dontList: string[];
  };
  segmentationTips: string[];
  estimatedReach: string;
  keyMetricsToTrack: string[];
  generatedAt: string;
}

export const campaignsTable = pgTable("campaigns", {
  id:         uuid("id").primaryKey().defaultRandom(),
  /** FK to business_profiles.id — which business owns this campaign. */
  businessId: integer("business_id"),
  name:       text("name").notNull(),
  platform:   text("platform").$type<CampaignPlatform>().notNull(),
  objective:  text("objective").notNull(),
  budget:     integer("budget").notNull().default(0),       // AOA
  status:     text("status").$type<CampaignStatus>().notNull().default("rascunho"),
  utmSlug:    text("utm_slug").notNull().unique(),          // matches utm_campaign on leads
  kitJson:    jsonb("kit_json").$type<CampaignKit | null>().default(null),
  totalSpend: integer("total_spend").notNull().default(0),  // manual input, AOA

  // ── Real ads via Zernio, paid in Kwanzas ────────────────────────────────────
  /** Campaign run length in days (lifetime budget spread over this window). */
  durationDays:   integer("duration_days").notNull().default(7),
  paymentStatus:  text("payment_status").$type<CampaignPaymentStatus>().notNull().default("nao_pago"),
  /** Merchant transaction id when paid via direct Multicaixa GPO charge. */
  paymentMerchantTransactionId: text("payment_merchant_transaction_id").unique(),
  /** How the budget was paid: "carteira" (wallet debit) or "multicaixa". */
  paymentMethod:  text("payment_method").$type<"carteira" | "multicaixa" | null>().default(null),
  paidAt:         timestamp("paid_at"),
  /** AOA per USD effective rate (incl. margin) locked at payment time. Money as text, never float. */
  fxRateAoaPerUsd: numeric("fx_rate_aoa_per_usd", { precision: 14, scale: 4 }),
  /** USD budget sent to the ads gateway, derived from budget AOA / fx rate. */
  budgetUsd:       numeric("budget_usd", { precision: 14, scale: 2 }),

  creativeStatus: text("creative_status").$type<CampaignCreativeStatus>().notNull().default("nenhum"),
  creativeJson:   jsonb("creative_json").$type<AdCreative | null>().default(null),
  creativeError:  text("creative_error"),

  publishStatus:  text("publish_status").$type<CampaignPublishStatus>().notNull().default("nao_publicada"),
  publishError:   text("publish_error"),
  zernioAdId:       text("zernio_ad_id"),
  zernioCampaignId: text("zernio_campaign_id"),
  zernioAdSetId:    text("zernio_ad_set_id"),
  /** True when created against the simulated gateway (no ZERNIO_API_KEY). */
  publishedSimulated: integer("published_simulated").notNull().default(0),

  // Metrics synced from the gateway
  syncedSpendUsd:    numeric("synced_spend_usd", { precision: 14, scale: 2 }),
  syncedImpressions: integer("synced_impressions").notNull().default(0),
  syncedClicks:      integer("synced_clicks").notNull().default(0),
  lastSyncAt:        timestamp("last_sync_at"),

  createdAt:  timestamp("created_at").notNull().defaultNow(),
  updatedAt:  timestamp("updated_at").notNull().defaultNow(),
});

// ─── Zod schemas ──────────────────────────────────────────────────────────────

export const createCampaignSchema = z.object({
  name:      z.string().min(2).max(120),
  platform:  z.enum(["google", "instagram", "facebook", "tiktok"]),
  objective: z.string().min(5).max(500),
  budget:    z.number().int().min(0).default(0),
  durationDays: z.number().int().min(1).max(90).default(7),
});

export const updateCampaignSchema = z.object({
  name:       z.string().min(2).max(120).optional(),
  status:     z.enum(["rascunho", "ativa", "pausada", "encerrada"]).optional(),
  budget:     z.number().int().min(0).optional(),
  totalSpend: z.number().int().min(0).optional(),
  durationDays: z.number().int().min(1).max(90).optional(),
});

export type Campaign = typeof campaignsTable.$inferSelect;
export type InsertCampaign = typeof campaignsTable.$inferInsert;
