import {
  pgTable,
  text,
  integer,
  timestamp,
  jsonb,
  uuid,
  numeric,
} from "drizzle-orm/pg-core";
import { z } from "zod/v4";

export type CampaignPlatform = "google" | "instagram" | "facebook" | "tiktok" | "meta";
export type CampaignStatus = "rascunho" | "ativa" | "pausada" | "encerrada";
/**
 * Objectives accepted by Zernio's Meta create-ad contract. The legacy aliases
 * remain in the type so historical campaigns can still be read safely.
 */
export type CampaignObjective =
  | "awareness"
  | "traffic"
  | "engagement"
  | "lead_generation"
  | "leads"
  | "sales";

export type CampaignDestination =
  | "whatsapp"
  | "download_app"
  | "linkealls_chat"
  | "catalog"
  | "product";

export type CampaignImageVariant = "original" | "suggested";
export type CampaignPolicyStatus = "approved" | "needs_review" | "rejected";

/** Payment state of the campaign budget (paid in Kz by the owner). */
export type CampaignPaymentStatus = "nao_pago" | "pendente" | "pago" | "falhado";
/** State of the AI-generated ad creative. */
export type CampaignCreativeStatus = "nenhum" | "a_gerar" | "pronto" | "erro";
/** State of the real ad published through the ads gateway (Zernio). */
export type CampaignPublishStatus =
  | "nao_publicada"
  | "a_publicar"
  | "em_revisao"
  | "ativa"
  | "pausada"
  | "encerrada"
  | "rejeitada"
  | "erro";

/** AI-generated ad creative (copy + media) ready for publication. */
export interface AdCreative {
  /** Products from the catalog the creative is built around. */
  productNames: string[];
  headline: string;
  body: string;
  /** Gateway CTA enum, e.g. SHOP_NOW, LEARN_MORE. */
  callToAction: string;
  /** "image" (Meta) or "video" (TikTok). */
  mediaType: "image" | "video";
  /** Served via /api/storage/objects/... */
  mediaUrl: string;
  /** Prompt/concept used, for regeneration transparency. */
  concept: string;
  generatedAt: string;
}

/** Configuration collected by the progressive Meta Ads wizard. */
export interface CampaignSetup {
  /** Where a click/conversation should take the person. */
  destination?: CampaignDestination;
  /** Required when the owner chooses a direct product link. */
  destinationUrl?: string | null;
  imageAnalysis?: {
    summary: string;
    detectedText: string[];
    detectedObjects: string[];
    policyStatus: CampaignPolicyStatus;
    policyIssues: string[];
    policyVersion: string;
    reviewedAt: string;
  } | null;
  /** Short explanation shown with the AI's automatic recommendation. */
  aiRecommendation?: {
    audienceReason: string;
    budgetReason: string;
    expectedReach: string;
    expectedReturn: string;
    recommendedBudgetAoa: number;
  } | null;
  audience: {
    location: string;
    /** Opaque Meta geo key returned by the targeting search. */
    locationId: string | null;
    ageMin: number;
    ageMax: number;
    gender: "all" | "female" | "male";
    interests: string;
    /** Opaque Meta interest ids matching the selected interest names. */
    interestIds: string[];
    excludedAudiences: string;
  };
  creative: {
    source: "upload" | "gemini";
    referenceImagePath: string | null;
    mediaPath: string | null;
    mediaMimeType: string | null;
    originalMediaPath?: string | null;
    suggestedMediaPath?: string | null;
    selectedVariant?: CampaignImageVariant;
    prompt: string;
    headline: string;
    body: string;
    callToAction: "SHOP_NOW" | "LEARN_MORE" | "CONTACT_US" | "ORDER_NOW" | "GET_OFFER";
  };
}

/** Copy variant generated by the AI. */
export interface CampaignCopy {
  headline: string;
  body: string;
  cta: string;
}

/** Full strategy kit per platform. */
export interface CampaignKit {
  audience: {
    demographics: string;
    interests: string;
    behaviours: string;
    excludedAudiences: string;
  };
  budgetAllocation: {
    suggestion: string;
    dailyBudget: string;
    bidStrategy: string;
  };
  copies: CampaignCopy[];
  creativeBrief: {
    format: string;
    visualConcept: string;
    doList: string[];
    dontList: string[];
  };
  segmentationTips: string[];
  estimatedReach: string;
  keyMetricsToTrack: string[];
  generatedAt: string;
}

export const campaignsTable = pgTable("campaigns", {
  id:         uuid("id").primaryKey().defaultRandom(),
  /** FK to business_profiles.id — which business owns this campaign. */
  businessId: integer("business_id"),
  name:       text("name").notNull(),
  platform:   text("platform").$type<CampaignPlatform>().notNull(),
  objective:  text("objective").notNull(),
  budget:     integer("budget").notNull().default(0),       // AOA
  status:     text("status").$type<CampaignStatus>().notNull().default("rascunho"),
  utmSlug:    text("utm_slug").notNull().unique(),          // matches utm_campaign on leads
  kitJson:    jsonb("kit_json").$type<CampaignKit | null>().default(null),
  campaignSetup: jsonb("campaign_setup").$type<CampaignSetup | null>().default(null),
  totalSpend: integer("total_spend").notNull().default(0),  // manual input, AOA

  // ── Real ads via Zernio, paid in Kwanzas ────────────────────────────────────
  /** Campaign run length in days (lifetime budget spread over this window). */
  durationDays:   integer("duration_days").notNull().default(7),
  paymentStatus:  text("payment_status").$type<CampaignPaymentStatus>().notNull().default("nao_pago"),
  /** Merchant transaction id when paid via direct Multicaixa GPO charge. */
  paymentMerchantTransactionId: text("payment_merchant_transaction_id").unique(),
  /** How the budget was paid: "carteira" (wallet debit) or "multicaixa". */
  paymentMethod:  text("payment_method").$type<"carteira" | "multicaixa" | null>().default(null),
  paidAt:         timestamp("paid_at"),
  /** AOA per USD effective rate (incl. margin) locked at payment time. Money as text, never float. */
  fxRateAoaPerUsd: numeric("fx_rate_aoa_per_usd", { precision: 14, scale: 4 }),
  /** USD budget sent to the ads gateway, derived from budget AOA / fx rate. */
  budgetUsd:       numeric("budget_usd", { precision: 14, scale: 2 }),

  creativeStatus: text("creative_status").$type<CampaignCreativeStatus>().notNull().default("nenhum"),
  creativeJson:   jsonb("creative_json").$type<AdCreative | null>().default(null),
  creativeError:  text("creative_error"),

  publishStatus:  text("publish_status").$type<CampaignPublishStatus>().notNull().default("nao_publicada"),
  publishError:   text("publish_error"),
  zernioAdId:       text("zernio_ad_id"),
  zernioCampaignId: text("zernio_campaign_id"),
  zernioAdSetId:    text("zernio_ad_set_id"),
  /** True when created against the simulated gateway (no ZERNIO_API_KEY). */
  publishedSimulated: integer("published_simulated").notNull().default(0),

  // Metrics synced from the gateway
  syncedSpendUsd:    numeric("synced_spend_usd", { precision: 14, scale: 2 }),
  syncedImpressions: integer("synced_impressions").notNull().default(0),
  syncedClicks:      integer("synced_clicks").notNull().default(0),
  lastSyncAt:        timestamp("last_sync_at"),
  publishedAt:       timestamp("published_at"),

  createdAt:  timestamp("created_at").notNull().defaultNow(),
  updatedAt:  timestamp("updated_at").notNull().defaultNow(),
});

/**
 * One row per Multicaixa (GPO) charge attempt for a campaign. The merchant
 * transaction id is immutable here even when the campaign row is retried with
 * a fresh id — so a delayed success webhook for an earlier attempt can always
 * be matched and audited (never silently lost).
 */
export const campaignPaymentAttemptsTable = pgTable("campaign_payment_attempts", {
  id:                    uuid("id").primaryKey().defaultRandom(),
  campaignId:            uuid("campaign_id").notNull(),
  merchantTransactionId: text("merchant_transaction_id").notNull().unique(),
  /** pendente | pago | falhado | pago_duplicado (paid after campaign already paid via another attempt) */
  status:                text("status").$type<"pendente" | "pago" | "falhado" | "pago_duplicado">().notNull().default("pendente"),
  createdAt:             timestamp("created_at").notNull().defaultNow(),
  updatedAt:             timestamp("updated_at").notNull().defaultNow(),
});

export type CampaignPaymentAttempt = typeof campaignPaymentAttemptsTable.$inferSelect;

// ─── Zod schemas ──────────────────────────────────────────────────────────────

export const createCampaignSchema = z.object({
  name:      z.string().min(2).max(120),
  platform:  z.enum(["google", "instagram", "facebook", "tiktok", "meta"]),
  objective: z.string().min(2).max(500),
  budget:    z.number().int().min(0).default(0),
  durationDays: z.number().int().min(1).max(90).default(7),
});

export const updateCampaignSchema = z.object({
  name:       z.string().min(2).max(120).optional(),
  status:     z.enum(["rascunho", "ativa", "pausada", "encerrada"]).optional(),
  budget:     z.number().int().min(0).optional(),
  totalSpend: z.number().int().min(0).optional(),
  durationDays: z.number().int().min(1).max(90).optional(),
  objective:   z.string().min(2).max(500).optional(),
});

const objectPathSchema = z.string().regex(/^\/objects\/[A-Za-z0-9/_-]+$/, "Caminho de object storage inválido");

export const campaignSetupSchema = z.object({
  destination: z.enum(["whatsapp", "download_app", "linkealls_chat", "catalog", "product"]).optional().default("catalog"),
  destinationUrl: z.string().trim().max(500).nullable().optional().default(null),
  imageAnalysis: z.object({
    summary: z.string().max(1000),
    detectedText: z.array(z.string().max(200)).max(30),
    detectedObjects: z.array(z.string().max(160)).max(30),
    policyStatus: z.enum(["approved", "needs_review", "rejected"]),
    policyIssues: z.array(z.string().max(300)).max(20),
    policyVersion: z.string().max(80),
    reviewedAt: z.string().datetime(),
  }).nullable().optional().default(null),
  aiRecommendation: z.object({
    audienceReason: z.string().max(600),
    budgetReason: z.string().max(600),
    expectedReach: z.string().max(160),
    expectedReturn: z.string().max(300),
    recommendedBudgetAoa: z.number().int().min(5000).max(10_000_000),
  }).nullable().optional().default(null),
  audience: z.object({
    location: z.string().trim().min(1).max(120),
    locationId: z.string().trim().max(200).nullable().optional().default(null),
    ageMin: z.number().int().min(13).max(65),
    ageMax: z.number().int().min(13).max(65),
    gender: z.enum(["all", "female", "male"]),
    interests: z.string().trim().max(500),
    interestIds: z.array(z.string().trim().min(1).max(80)).max(25).optional().default([]),
    excludedAudiences: z.string().trim().max(500),
  }).refine((value) => value.ageMax >= value.ageMin, {
    message: "A idade máxima deve ser igual ou superior à mínima",
    path: ["ageMax"],
  }),
  creative: z.object({
    source: z.enum(["upload", "gemini"]),
    referenceImagePath: objectPathSchema.nullable(),
    mediaPath: objectPathSchema.nullable(),
    mediaMimeType: z.string().max(80).nullable(),
    originalMediaPath: objectPathSchema.nullable().optional().default(null),
    suggestedMediaPath: objectPathSchema.nullable().optional().default(null),
    selectedVariant: z.enum(["original", "suggested"]).optional().default("original"),
    prompt: z.string().trim().max(1000),
    headline: z.string().trim().max(40),
    body: z.string().trim().max(300),
    callToAction: z.enum(["SHOP_NOW", "LEARN_MORE", "CONTACT_US", "ORDER_NOW", "GET_OFFER"]),
  }),
});

export type Campaign = typeof campaignsTable.$inferSelect;
export type InsertCampaign = typeof campaignsTable.$inferInsert;
