import {
  pgTable,
  text,
  integer,
  timestamp,
  jsonb,
  uuid,
} from "drizzle-orm/pg-core";
import { z } from "zod/v4";

export type CampaignPlatform = "google" | "instagram" | "facebook" | "tiktok";
export type CampaignStatus = "rascunho" | "ativa" | "pausada" | "encerrada";

/** Copy variant generated by the AI. */
export interface CampaignCopy {
  headline: string;
  body: string;
  cta: string;
}

/** Full strategy kit per platform. */
export interface CampaignKit {
  audience: {
    demographics: string;
    interests: string;
    behaviours: string;
    excludedAudiences: string;
  };
  budgetAllocation: {
    suggestion: string;
    dailyBudget: string;
    bidStrategy: string;
  };
  copies: CampaignCopy[];
  creativeBrief: {
    format: string;
    visualConcept: string;
    doList: string[];
    dontList: string[];
  };
  segmentationTips: string[];
  estimatedReach: string;
  keyMetricsToTrack: string[];
  generatedAt: string;
}

export const campaignsTable = pgTable("campaigns", {
  id:         uuid("id").primaryKey().defaultRandom(),
  name:       text("name").notNull(),
  platform:   text("platform").$type<CampaignPlatform>().notNull(),
  objective:  text("objective").notNull(),
  budget:     integer("budget").notNull().default(0),       // AOA
  status:     text("status").$type<CampaignStatus>().notNull().default("rascunho"),
  utmSlug:    text("utm_slug").notNull().unique(),          // matches utm_campaign on leads
  kitJson:    jsonb("kit_json").$type<CampaignKit | null>().default(null),
  totalSpend: integer("total_spend").notNull().default(0),  // manual input, AOA
  createdAt:  timestamp("created_at").notNull().defaultNow(),
  updatedAt:  timestamp("updated_at").notNull().defaultNow(),
});

// ─── Zod schemas ──────────────────────────────────────────────────────────────

export const createCampaignSchema = z.object({
  name:      z.string().min(2).max(120),
  platform:  z.enum(["google", "instagram", "facebook", "tiktok"]),
  objective: z.string().min(5).max(500),
  budget:    z.number().int().min(0).default(0),
});

export const updateCampaignSchema = z.object({
  name:       z.string().min(2).max(120).optional(),
  status:     z.enum(["rascunho", "ativa", "pausada", "encerrada"]).optional(),
  budget:     z.number().int().min(0).optional(),
  totalSpend: z.number().int().min(0).optional(),
});

export type Campaign = typeof campaignsTable.$inferSelect;
export type InsertCampaign = typeof campaignsTable.$inferInsert;
